#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ENV_FILE="${MINER_ENV_FILE:-${SCRIPT_DIR}/miner.env}"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Missing env file: ${ENV_FILE}"
  echo "Create it from ${SCRIPT_DIR}/miner.env.example"
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "${ENV_FILE}"
set +a

NETUID="${NETUID:-54}"
SUBTENSOR_NETWORK="${SUBTENSOR_NETWORK:-finney}"
CHAIN_ENDPOINT="${CHAIN_ENDPOINT:-wss://entrypoint-finney.opentensor.ai:443}"
MINER_MODEL_NAME="${MINER_MODEL_NAME:-llama3.1:latest}"
OLLAMA_URL="${OLLAMA_URL:-http://127.0.0.1:11434}"
MINER_AXON_PORT="${MINER_AXON_PORT:-8091}"
AXON_EXTERNAL_IP="${AXON_EXTERNAL_IP:-}"
AXON_EXTERNAL_PORT="${AXON_EXTERNAL_PORT:-}"
MINER_ENV_PATH="${MINER_ENV_PATH:-${PROJECT_ROOT}/miner_env}"
SN54_IMAGE_GENERATION_BACKEND="${SN54_IMAGE_GENERATION_BACKEND:-comfyui}"
COMFYUI_BASE_URL="${COMFYUI_BASE_URL:-http://127.0.0.1:20007}"
COMFYUI_REQUEST_TIMEOUT_SECONDS="${COMFYUI_REQUEST_TIMEOUT_SECONDS:-60}"
COMFYUI_EXECUTION_TIMEOUT_SECONDS="${COMFYUI_EXECUTION_TIMEOUT_SECONDS:-300}"
COMFYUI_POLL_INTERVAL_SECONDS="${COMFYUI_POLL_INTERVAL_SECONDS:-1.0}"
COMFYUI_SERIALIZE_REQUESTS="${COMFYUI_SERIALIZE_REQUESTS:-true}"
LOG_LEVEL="${LOG_LEVEL:-debug}"
LOG_DIR="${LOG_DIR:-${PROJECT_ROOT}/logs}"
RUN_DIR="${RUN_DIR:-${PROJECT_ROOT}/run}"
MINER_LOG_FILE="${MINER_LOG_FILE:-${LOG_DIR}/sn54-miner.log}"
MINER_PID_FILE="${MINER_PID_FILE:-${RUN_DIR}/sn54-miner.pid}"
DASHBOARD_LOG_FILE="${DASHBOARD_LOG_FILE:-${LOG_DIR}/sn54-dashboard.log}"
DASHBOARD_PID_FILE="${DASHBOARD_PID_FILE:-${RUN_DIR}/sn54-dashboard.pid}"
DASHBOARD_ENABLED="${DASHBOARD_ENABLED:-true}"
DASHBOARD_HOST="${DASHBOARD_HOST:-127.0.0.1}"
DASHBOARD_PORT="${DASHBOARD_PORT:-8810}"
PORT_HEALTH_ENABLED="${PORT_HEALTH_ENABLED:-true}"
PORT_HEALTH_CHECK_SECONDS="${PORT_HEALTH_CHECK_SECONDS:-60}"
PORT_HEALTH_FAILURE_THRESHOLD="${PORT_HEALTH_FAILURE_THRESHOLD:-1}"
PORT_HEALTH_RECOVERY_THRESHOLD="${PORT_HEALTH_RECOVERY_THRESHOLD:-1}"
PORT_HEALTH_CONNECT_TIMEOUT_SECONDS="${PORT_HEALTH_CONNECT_TIMEOUT_SECONDS:-8}"
PORT_HEALTH_ALERT_COOLDOWN_MINUTES="${PORT_HEALTH_ALERT_COOLDOWN_MINUTES:-30}"
PORT_HEALTH_IP_DISCOVERY_URLS="${PORT_HEALTH_IP_DISCOVERY_URLS:-https://api.ipify.org,https://ifconfig.me/ip}"
PORT_HEALTH_CHECK_URL="${PORT_HEALTH_CHECK_URL:-https://ports.yougetsignal.com/check-port.php}"

TELEGRAM_NOTIFIER_ENABLED="${TELEGRAM_NOTIFIER_ENABLED:-true}"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-}"
TELEGRAM_POLL_SECONDS="${TELEGRAM_POLL_SECONDS:-1.0}"
TELEGRAM_FLUSH_SECONDS="${TELEGRAM_FLUSH_SECONDS:-5.0}"
TELEGRAM_HEARTBEAT_SECONDS="${TELEGRAM_HEARTBEAT_SECONDS:-300.0}"
TELEGRAM_NO_TRAFFIC_ALERT_MINUTES="${TELEGRAM_NO_TRAFFIC_ALERT_MINUTES:-20}"
TELEGRAM_NO_TRAFFIC_ALERT_COOLDOWN_MINUTES="${TELEGRAM_NO_TRAFFIC_ALERT_COOLDOWN_MINUTES:-30}"
TELEGRAM_MAX_LINES_PER_MESSAGE="${TELEGRAM_MAX_LINES_PER_MESSAGE:-60}"
TELEGRAM_MAX_CHARS_PER_MESSAGE="${TELEGRAM_MAX_CHARS_PER_MESSAGE:-3500}"
TELEGRAM_LOG_FILE="${TELEGRAM_LOG_FILE:-${LOG_DIR}/sn54-telegram.log}"
TELEGRAM_PID_FILE="${TELEGRAM_PID_FILE:-${RUN_DIR}/sn54-telegram.pid}"
TELEGRAM_STATE_FILE="${TELEGRAM_STATE_FILE:-${RUN_DIR}/sn54-telegram.state.json}"

mkdir -p "${LOG_DIR}" "${RUN_DIR}"
if [[ -n "${PHASE4_VALIDATOR_SEED_IMAGE_DIR:-}" ]]; then
  mkdir -p "${PHASE4_VALIDATOR_SEED_IMAGE_DIR}"
fi
if [[ -n "${PHASE4_DASHBOARD_PREVIEW_DIR:-}" ]]; then
  mkdir -p "${PHASE4_DASHBOARD_PREVIEW_DIR}"
fi
